### ISSUE TITLE
Omnic Improperly Displaying Currently Playing Track

### ISSUE THREAD

**Issue by Nornec** [Dalf32/Omnic#1]
Occurred after playing several short-length songs from the album "East-West Blast Test" by Chris Dodge & Dave Witte, located in my library. !history still works as expected.

**Comment by Dalf32** [comment]
This was occurring when the API request failed and we were unable to extract the artist; the resulting exception was crashing the update thread. Resolved with some additional error checking/handling and a new command to forcibly restart the update thread if needed.
